name:          Code Guide bởi SolisLab
description:   Tiêu chuẩn Code linh hoạt, thuận tiện và dễ sử dụng.
url:           https://khoipro.github.io/code-guide-vn/

markdown:      rdiscount
permalink:     pretty
pygments:      true
