name:          Code Guide bởi SolisLab
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           https://khoipro.github.io/code-guide-vn/

markdown:      rdiscount
permalink:     pretty
pygments:      true
